version: '3'

services:
  # nginx代理配置, 用于一键部署生产环境
  web:
    image: nginx:stable
    volumes:
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${BA_PROJECT_PATH}:/var/www"
      - "./docker/logs/nginx:/var/log/nginx"
      - "./docker/ssl:/var/ssl"
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
  # 可用于生产部署
  php:
    image: ${BA_IMAGE}
    build:
      args:
        - PHP_VERSION=${PHP_VERSION}
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - "${BA_PROJECT_PATH}:/var/www"
    links:
      - mysql
  # 安装php依赖包
  ba-php-install:
    image: ${BA_IMAGE}
    volumes:
      - "${BA_PROJECT_PATH}:/var/www"
    command: composer install
  # 安装前端依赖包
  ba-web-install:
    image: ${BA_IMAGE}
    working_dir: /var/www/web
    volumes:
      - "${BA_PROJECT_PATH}:/var/www"
    command: yarn
  # 后端开发
  ba-php-dev:
    image: ${BA_IMAGE}
    working_dir: /var/www
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "${BA_PROJECT_PATH}:/var/www"
    command: php think run
    links:
      - mysql
  # 前端开发
  ba-web-dev:
    image: ${BA_IMAGE}
    working_dir: /var/www/web
    ports:
      - "127.0.0.1:1818:1818"
    volumes:
      - "${BA_PROJECT_PATH}:/var/www"
    command: yarn dev
  # 数据库
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/initdb:/docker-entrypoint-initdb.d"
  # 生成证书, 在项目安装完成后修改 .env 文件并执行 docker compose up cerbot
  certbot:
    image: certbot/certbot
    depends_on:
      - web
    volumes:
      - "${BA_PROJECT_PATH}/public/:/var/www/"
      - "./docker/logs/certbot:/var/log/letsencrypt"
      - "./docker/ssl:/etc/letsencrypt"
    command: certonly --force-renewal --email ${CERTBOT_EMAIL} --domain ${CERTBOT_DOMAIN} --agree-tos --webroot -w /var/www -n
